name: Worker

on:
  workflow_dispatch:
      inputs:
        url:
          type: string
          default: https://raw.githubusercontent.com/aiboboxx/clashfree/refs/heads/main/clash.yml
          required: false
        output:
          type: string
          default: worker.yaml
          required: false

jobs:
  worker:
    runs-on: ubuntu-latest
    env:
      url: ${{ github.event.inputs.url }}
      output: ${{ github.event.inputs.output }}
        
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependency
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run
        run: |
          python -m worker --url $url --output $output

      - name: Commit and Push
        id: commit_n_push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "$output"
          git commit -m "Update clash.yaml."
          git push
        if: ${{ github.ref == 'refs/heads/main' }}

          
          
