name: Worker

on:
  workflow_dispatch:

jobs:
  worker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependency
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run
        run: |
          python -m worker

      - name: Commit and Push
        id: commit_n_push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add clash.yaml
          git commit -m "Update clash.yaml."
          git push
        if: ${{ github.ref == 'refs/heads/main' }}

          
          
