name: Worker

on:
  workflow_dispatch:

jobs:
  worker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependency
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run
        run: |
          python -m worker

      - name: Commit
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add clash.yaml
          git commit -m "Update clash.yaml."
        if: ${{ github.ref == 'refs/heads/main' }}

      - name: Push
        uses: ad-m/github-push-action@master
        if: ${{ steps.commit.outputs.hasChange == 'true' }}
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: ${{ github.ref }}

          
          
